### ISSUE TITLE
  Call to undefined function CrCms\ElasticSearch\array_pull()

### ISSUE THREAD

**Issue by pooy** [crcms/elasticsearch#23]
query：
        $builder = $this->builder->index('index')->type('type');
        $result = $builder->whereTerm('id',10015)->first();

error:
 Call to undefined function CrCms\ElasticSearch\array_pull()
  at vendor/crcms/elasticsearch/src/Grammar.php:62

**Comment by simon28082** [comment]
You use version is ?
Or You can use the dev-master version
