### ISSUE TITLE
orWhereMatch的默认参数有问题

### ISSUE THREAD

**Issue by tonsionw** [crcms/elasticsearch#4]
public function orWhereMatch($field, $value, $boolean = 'and'): self
    {
        return $this->whereMatch($field, $value, $boolean);
    }
应该是：
public function orWhereMatch($field, $value, $boolean = 'or'): self
    {
        return $this->whereMatch($field, $value, $boolean);
    }

**Comment by crcms** [comment]
@tonsionw 非常感谢，你也可以自己提pr

**Comment by tonsionw** [comment]
还少了matchphase这个



---原始邮件---
发件人: "simon"<notifications@github.com&gt;
发送时间: 2019年12月17日(周二) 下午5:51
收件人: "crcms/elasticsearch"<elasticsearch@noreply.github.com&gt;;
抄送: "tonsionw"<397610577@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [crcms/elasticsearch] orWhereMatch的默认参数有问题 (#4)



@tonsionw 非常感谢，你也可以自己提pr
