### ISSUE TITLE
关于 No alive nodes found in your cluster in 问题

### ISSUE THREAD

**Issue by yanhongwei6** [crcms/elasticsearch#6]
composer下来后运行查询报错
product.ERROR: Elasticsearch\Common\Exceptions\NoNodesAvailableException: No alive nodes found in your cluster in F:\WNMP\WWW\product_houtai_hn\vendor\elasticsearch\elasticsearch\src\Elasticsearch\ConnectionPool\StaticNoPingConnectionPool.php:53
Stack trace:

百度好久了找不到解决方法呃。。。

**Comment by crcms** [comment]
这是没有可用节点啊，请尝试手动连接你的es，在本包中config/search.php中的host需要增加端口，如:
127.0.0.1:9000

**Comment by yanhongwei6** [comment]
收到谢谢楼主，，问题已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"simon"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月3日(星期一) 晚上6:17
收件人:&nbsp;"crcms/elasticsearch"<elasticsearch@noreply.github.com&gt;;
抄送:&nbsp;"颜洪委"<295270711@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [crcms/elasticsearch] 关于 No alive nodes found in your cluster in 问题 (#6)




这是没有可用节点啊，请尝试手动连接你的es，在本包中config/search.php中的host需要增加端口，如:
 127.0.0.1:9000
